/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as TuningRouteImport } from './routes/tuning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const TuningRoute = TuningRouteImport.update({
  id: '/tuning',
  path: '/tuning',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/ready': typeof ReadyRoute
  '/tuning': typeof TuningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/ready': typeof ReadyRoute
  '/tuning': typeof TuningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/ready': typeof ReadyRoute
  '/tuning': typeof TuningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/health' | '/ready' | '/tuning'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/health' | '/ready' | '/tuning'
  id: '__root__' | '/' | '/health' | '/ready' | '/tuning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  ReadyRoute: typeof ReadyRoute
  TuningRoute: typeof TuningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuning': {
      id: '/tuning'
      path: '/tuning'
      fullPath: '/tuning'
      preLoaderRoute: typeof TuningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  ReadyRoute: ReadyRoute,
  TuningRoute: TuningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
