/** Shared Tailwind theme utilities for the self-hosted and cloud document roots. */
export const themeClassName = [
  "[color-scheme:light] dark:[color-scheme:dark] font-sans bg-background text-foreground",
  "[--paper:#f3f1e9] dark:[--paper:#171e1b]",
  "[--glow:#fcfbf6] dark:[--glow:#222d26]",
  "[--ink:#273e35] dark:[--ink:#e2e9d8]",
  "[--muted:#747c72] dark:[--muted:#a5af9d]",
  "[--line:#d9ddd1] dark:[--line:#3b473c]",
  "[--accent:#30664b] dark:[--accent:#b0cfa1]",
  "[--soft:#e5eadd] dark:[--soft:#303e32]",
  "[--hover:#dce6d2] dark:[--hover:#3b503e]",
  "[--white:#fbfaf5] dark:[--white:#222b24]",
  "[--dock:#efeee6] dark:[--dock:#1c2520]",
  "[--string:#87917e] dark:[--string:#899780]",
  "[--fret:#c3cbbd] dark:[--fret:#465643]",
  "[--dot-text:#fbfaf5] dark:[--dot-text:#1c271e]",
  "[--success:#56825c] dark:[--success:#b1d69c]",
  "[--muted-bg:#eae5dd] dark:[--muted-bg:#3d342e]",
  "[--muted-ink:#826459] dark:[--muted-ink:#d7b6a4]",
  "[--background:var(--paper)]",
  "[--foreground:var(--ink)]",
  "[--primary:var(--accent)]",
  "[--primary-foreground:var(--dot-text)]",
  "[--secondary:var(--soft)]",
  "[--secondary-foreground:var(--ink)]",
  "[--destructive:#a94338] dark:[--destructive:#b95f57]",
  "[--destructive-foreground:#fff7f3] dark:[--destructive-foreground:#fff7f3]",
  "[--radius:0.625rem]",
].join(" ");
