import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Song } from "../packages/contracts/src/index.ts";
import { parseChart } from "../packages/music/src/index.ts";

export type Candidate = {
  rank: number;
  title: string;
  attribution: string;
  category: string;
  revision?: number;
};

export function buildCatalog(
  candidates: readonly Candidate[],
  charts: ReadonlyMap<number, string>,
): { songs: Song[]; pending: number[] } {
  const ranks = new Set<number>();
  const pending: number[] = [];
  const songs: Song[] = [];
  for (const candidate of candidates) {
    if (
      !Number.isInteger(candidate.rank) ||
      candidate.rank < 1 ||
      candidate.rank > 100
    )
      throw new Error(`Invalid rank: ${candidate.rank}`);
    if (ranks.has(candidate.rank))
      throw new Error(`Duplicate rank: ${candidate.rank}`);
    ranks.add(candidate.rank);
    if (!candidate.title.trim())
      throw new Error(`Missing title at rank ${candidate.rank}`);
    const chart = charts.get(candidate.rank);
    if (!chart) {
      pending.push(candidate.rank);
      continue;
    }
    if (!candidate.attribution.trim())
      throw new Error(`Missing attribution at rank ${candidate.rank}`);
    const revision = candidate.revision ?? 1;
    if (!Number.isInteger(revision) || revision < 1)
      throw new Error(`Invalid revision at rank ${candidate.rank}`);
    const { chords, tuning } = parseChart(chart);
    songs.push({
      id: `catalog:starter:${String(candidate.rank).padStart(3, "0")}`,
      title: candidate.title,
      attribution: candidate.attribution,
      chords,
      sourceChart: chart,
      tuning,
      revision,
      catalog: true,
    });
  }
  return { songs, pending };
}

async function main() {
  const root = fileURLToPath(new URL("../", import.meta.url));
  const candidates = JSON.parse(
    await readFile(resolve(root, "docs/catalog/candidates.json"), "utf8"),
  ) as Candidate[];
  const charts = new Map<number, string>();
  for (const candidate of candidates) {
    const path = resolve(
      root,
      `docs/catalog/charts/${String(candidate.rank).padStart(3, "0")}.txt`,
    );
    try {
      charts.set(candidate.rank, await readFile(path, "utf8"));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
  }
  const { songs, pending } = buildCatalog(candidates, charts);
  const output = resolve(root, "packages/music/src/catalog-curated.ts");
  await writeFile(
    output,
    `import type { Song } from "@cadence/contracts";\n\n// Generated by pnpm catalog:prepare. Review sources in docs/catalog before release.\nexport const curatedSongs: readonly Song[] = ${JSON.stringify(songs, null, 2)};\n`,
  );
  process.stdout.write(
    `Prepared ${songs.length} global catalog songs; ${pending.length} pending.\n`,
  );
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
)
  await main();
